_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cache_control_override: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_update: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  draggableviews: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_clone: 0
  entity_clone_extras: 0
  entity_reference_revisions: 0
  features: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  flexslider: 0
  flexslider_fields: 0
  flexslider_views: 0
  fontawesome: 0
  geofield: 0
  help: 0
  history: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  search_api: 0
  search_api_db: 0
  shortcut: 0
  simple_gmap: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  social_link_field: 0
  social_media_links: 0
  social_media_links_field: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  telephone: 0
  telephone_validation: 0
  text: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_fieldsets: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable: 0
  classy: 0
  exam: 0
profile: standard
