cloneable_entities:
  - block
  - block_content_type
  - block_content
  - comment_type
  - comment
  - contact_message
  - contact_form
  - editor
  - features_bundle
  - field_storage_config
  - field_config
  - file
  - filter_format
  - image_style
  - media
  - media_type
  - menu_link_content
  - node_type
  - node
  - path_alias
  - search_page
  - search_api_task
  - search_api_server
  - search_api_index
  - shortcut
  - shortcut_set
  - action
  - menu
  - taxonomy_vocabulary
  - taxonomy_term
  - taxonomy_menu
  - tour
  - user_role
  - user
  - view
  - paragraph
  - paragraphs_type
  - entity_form_display
  - entity_view_display
  - entity_form_mode
  - entity_view_mode
  - base_field_override
  - date_format
  - webform
  - webform_submission
  - webform_options
  - slick
  - simple_like
  - like
  - flagging
  - flag
  - flexslider
